version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin        # Change to your desired username
      POSTGRES_PASSWORD: admin123    # Change to a strong password
      POSTGRES_DB: srsi      # Default database to create
    ports:
      - "5432:5432"                # Host:Container port mapping
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persistent storage
    networks:
      - srsi_network

networks:
  srsi_network:
    driver: bridge

volumes:
  postgres_data: